name: build
on: push
jobs:
  main:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with: { node-version: 12 }
      - run: echo "::set-env name=YARN_CACHE_DIR::$(yarn cache dir)"
      - uses: actions/cache@v1
        with:
          path: ${{ env.YARN_CACHE_DIR }}
          key: yarn-${{ hashFiles('package.json') }}-${{ hashFiles('packages/**/package.json') }}
          restore-keys: |
            yarn-${{ hashFiles('package.json') }}-
            yarn-
      - run: yarn
      - run: yarn build
      - name: The working tree is clean.
        run: "[[ -z $(git status --porcelain) ]]"
      - name: Show the working tree status.
        if: failure()
        run: |
          git status
          git diff
